### ISSUE TITLE
关于数据源

### ISSUE THREAD

**Issue by aquarius-wing** [acabin/quantorio#2]
请问作者这些配方数据是哪里来的啊?是调用某个api还是自己手动输入的?...

**Comment by RuijieYu** [comment]
没有仔细看程序，但是原版的配方数据是没有加密的lua代码，所以作者可能是读取这个文件得到的数据

**Comment by garveen** [comment]
从SteamLibrary/steamapps/common/Factorio/data/base/prototypes拿的
