### ISSUE TITLE
有没有计划支持高成本配方难度?

### ISSUE THREAD

**Issue by crystalsis** [acabin/quantorio#5]
现在可以把配方难度系列改成高成本
这样有一个电路板会需要10个铜线电力矿机会是20铁板10齿轮5电路板之类的
这样的话量化就不一样了,而且不是相同比例变高的,没法简单倍增

**Comment by garveen** [comment]
代码里面有，没开放出来，有空会做，欢迎pr

**Comment by garveen** [comment]
Implemented
